// src/components/Button/Button.tsx
"use client"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"
import React, { forwardRef } from "react"
import { animated, useSpring } from "@react-spring/web"
import { cn } from "../../utils/utils"
import { useMeasure } from "../../hooks"
import Loader from "../Loader"

export const buttonVariants = cva(
  "box-border inline-flex cursor-pointer items-center justify-center rounded-md border border-transparent align-middle leading-4 transition-transform ease-in enabled:active:scale-95 disabled:pointer-events-none disabled:opacity-50 ring-offset-white dark:ring-offset-black focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gray-500 focus-visible:ring-offset-2",
  {
    variants: {
      variant: {
        default:
          "border-gray-400 bg-white enabled:hover:border-black dark:border-gray-500 dark:bg-brand-dark-500 dark:text-white dark:enabled:hover:border-gray-300",
        primary: "bg-blue-500 text-white hover:bg-blue-600 active:border-blue-700",
        success: "bg-green-500 text-white hover:bg-green-600 active:border-green-700",
        warning: "bg-yellow-500 text-white hover:bg-yellow-600 active:border-yellow-700",
        danger: "bg-red-500 text-white hover:bg-red-600 active:border-red-700",
        link: "bg-transparent enabled:hover:underline text-blue-500 hover:text-blue-600",
        light: "border-gray-400 bg-white enabled:hover:border-black",
        dark: "border-gray-500 bg-brand-dark-200 text-white enabled:hover:border-white",
        ghost:
          "bg-transparent text-black hover:bg-gray-100 active:bg-gray-200 dark:hover:bg-brand-dark-500 dark:active:bg-brand-dark-600 dark:text-white",
      },
      size: {
        default: "px-5 py-2.5 h-10",
        sm: "h-9 px-4",
        lg: "h-11 px-8",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
  loading?: boolean
}

/**
 * `Button` allows us to create a consistent style for all of our user actions.
 */
const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  (
    {
      asChild = false,
      variant = "default",
      size = "default",
      loading = false,
      type = "button",
      className,
      children,
      ...props
    },
    ref
  ) => {
    const Comp = asChild ? Slot : "button"
    const [bindLoader, { width: loaderWidth }] = useMeasure<HTMLDivElement>()
    const loaderAnimationProps = useSpring({
      width: loading ? loaderWidth * 2 : 0,
      marginLeft: loading ? 8 : 0,
    })

    const loaderVariant = () => {
      switch (variant) {
        case "default":
          return "default"
        case "ghost":
          return "default"
        case "link":
          return "primary"
        case "light":
          return "black"
        case "dark":
          return "white"
        default:
          return "white"
      }
    }

    return (
      <Comp ref={ref} type={type} className={cn(buttonVariants({ variant, size }), className)} {...props}>
        <div className="flex flex-row flex-nowrap content-center items-center">
          {children}
          {loading && (
            <animated.div style={loaderAnimationProps}>
              <Loader
                size="sm"
                className="text-[1.5px]"
                variant={loaderVariant()}
                ringColor="transparent"
                {...bindLoader}
              />
            </animated.div>
          )}
        </div>
      </Comp>
    )
  }
)
Button.displayName = "Button"

export default Button

// src/lib/components/ui/button/button.svelte
<script lang="ts" module>
	import { cn, type WithElementRef } from '$lib/utils/shadcn.js';
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from 'svelte/elements';
	import { type VariantProps, tv } from 'tailwind-variants';

	export const buttonVariants = tv({
		base: "focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive inline-flex shrink-0 items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium outline-none transition-all focus-visible:ring-[3px] disabled:pointer-events-none disabled:opacity-50 aria-disabled:pointer-events-none aria-disabled:opacity-50 [&_svg:not([class*='size-'])]:size-4 [&_svg]:pointer-events-none [&_svg]:shrink-0",
		variants: {
			variant: {
				default: 'bg-primary text-primary-foreground shadow-xs hover:bg-primary/90',
				destructive:
					'bg-destructive shadow-xs hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60 text-white',
				outline:
					'bg-background shadow-xs hover:bg-accent hover:text-accent-foreground dark:bg-input/30 dark:border-input dark:hover:bg-input/50 border',
				secondary: 'bg-secondary text-secondary-foreground shadow-xs hover:bg-secondary/80',
				ghost: 'hover:bg-accent hover:text-accent-foreground dark:hover:bg-accent/50',
				link: 'text-primary underline-offset-4 hover:underline'
			},
			size: {
				default: 'h-9 px-4 py-2 has-[>svg]:px-3',
				sm: 'h-8 gap-1.5 rounded-md px-3 has-[>svg]:px-2.5',
				lg: 'h-10 rounded-md px-6 has-[>svg]:px-4',
				icon: 'size-9'
			}
		},
		defaultVariants: {
			variant: 'default',
			size: 'default'
		}
	});

	export type ButtonVariant = VariantProps<typeof buttonVariants>['variant'];
	export type ButtonSize = VariantProps<typeof buttonVariants>['size'];

	export type ButtonProps = WithElementRef<HTMLButtonAttributes> &
		WithElementRef<HTMLAnchorAttributes> & {
			variant?: ButtonVariant;
			size?: ButtonSize;
		};
</script>

<script lang="ts">
	let {
		class: className,
		variant = 'default',
		size = 'default',
		ref = $bindable(null),
		href = undefined,
		type = 'button',
		disabled,
		children,
		...restProps
	}: ButtonProps = $props();
</script>

{#if href}
	<a
		bind:this={ref}
		data-slot="button"
		class={cn(buttonVariants({ variant, size }), className)}
		href={disabled ? undefined : href}
		aria-disabled={disabled}
		role={disabled ? 'link' : undefined}
		tabindex={disabled ? -1 : undefined}
		{...restProps}
	>
		{@render children?.()}
	</a>
{:else}
	<button
		bind:this={ref}
		data-slot="button"
		class={cn(buttonVariants({ variant, size }), className)}
		{type}
		{disabled}
		{...restProps}
	>
		{@render children?.()}
	</button>
{/if}
