// components/Button/Button.tsx
import { cva, type VariantProps } from "class-variance-authority"
import { twMerge } from "tailwind-merge"

const button = cva(
  [
    "justify-center",
    "inline-flex",
    "items-center",
    "rounded-xl",
    "text-center",
    "border",
    "border-blue-400",
    "transition-colors",
    "delay-50",
  ],
  {
    variants: {
      intent: {
        primary: ["bg-blue-400", "text-white", "hover:enabled:bg-blue-700"],
        secondary: ["bg-transparent", "text-blue-400", "hover:enabled:bg-blue-400", "hover:enabled:text-white"],
      },
      size: {
        sm: ["min-w-20", "h-full", "min-h-10", "text-sm", "py-1.5", "px-4"],
        lg: ["min-w-32", "h-full", "min-h-12", "text-lg", "py-2.5", "px-6"],
      },
      underline: { true: ["underline"], false: [] },
    },
    defaultVariants: {
      intent: "primary",
      size: "lg",
    },
  }
)

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLAnchorElement>, VariantProps<typeof button> {
  underline?: boolean
  href: string
}

export function Button({ className, intent, size, underline, ...props }: ButtonProps) {
  return (
    <a className={twMerge(button({ intent, size, className, underline }))} {...props}>
      {props.children}
    </a>
  )
}

// src/lib/components/Button.svelte
<script lang="ts">
	import { cva, type VariantProps } from 'class-variance-authority';
	import { twMerge } from 'tailwind-merge';

	const button = cva(['btn'], {
		variants: {
			intent: {
				primary: ['btn-primary'],
				secondary: ['btn-outline']
			},
			size: {
				sm: ['btn-sm'],
				lg: ['btn-lg']
			},
			underline: { true: ['underline'], false: [] }
		},
		defaultVariants: {
			intent: 'primary',
			size: 'lg'
		}
	});

	interface ButtonProps {
		intent?: 'primary' | 'secondary';
		size?: 'sm' | 'lg';
		underline?: boolean;
		href?: string;
		children?: any;
		class?: string;
	}

	let {
		intent,
		size,
		underline,
		href,
		children,
		class: className,
		...props
	}: ButtonProps = $props();
</script>

{#if href}
	<a {href} class={twMerge(button({ intent, size, class: className, underline }))} {...props}>
		{@render children?.()}
	</a>
{:else}
	<button class={twMerge(button({ intent, size, class: className, underline }))} {...props}>
		{@render children?.()}
	</button>
{/if}
